version: '3.8'

services:
  web:
    build:
      context: ./app
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=${REDIS_URL}
    env_file:
      - ./.env
    volumes:
      - ./app:/app

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - BOT_TOKEN=${MONGO_URL}
      - MONGO_URL=${MONGO_URL}

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  bot:
    build:
      context: ./bot
    command: [ "python", "main.py" ]
    depends_on:
      - web
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=${API_URL}
    env_file:
      - ./.env
    volumes:
      - ./bot:/bot
